project:
  type: book
  output-dir: docs

book:
  title: "Regression"
  author: "Colton Gearhart"
  date: "12/4/23"
  cover-image: regression.png
  chapters:
    - index.qmd

    - part: part1-slr.qmd
      chapters:
        - notes-slr.qmd
        - notes-inference.qmd
        - notes-diagnostics-and-remedial-measures.qmd
        # - notes-other-topics-in-regression.qmd
        - notes-matrix-slr.qmd
        

    - part: part2-mlr.qmd
      chapters:
        - notes-multiple-regression-1.qmd
        - notes-multiple-regression-2.qmd

        
format:
  html:
    theme: flatly
    code-link: true
    #code-fold: show
    code-tools: true
    code-block-border-left: "#2C3E50"
    highlight-style: github
    
title-block-banner: true
